name: Check for new core technologies

on:
  #schedule:
  # - cron:  '0 10 * * *'
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true

jobs:
  nuget-slack-notifications:
    name: Check for core technology package updates
    runs-on: ubuntu-latest
    continue-on-error: false
    
    env:
      scan-tool-path: ${{ github.workspace }}/.github/workflows/scripts/NugetSlackNotifications

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for updates to core technology packages
        run: dotnet run --project ${{ env.scan-tool-path }}

           
